# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hex_value', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Color'),
        ),
    ]
