# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171018_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='color',
        ),
        migrations.AddField(
            model_name='cat',
            name='primary_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.Color'),
        ),
        migrations.AddField(
            model_name='cat',
            name='second_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.Color'),
        ),
    ]
