# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171020_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.FileField(blank=True, upload_to='blog/uploads/postagem'),
        ),
    ]
